### ISSUE TITLE
[Feature Request] Automatically generate SSH keys

### ISSUE THREAD

**Issue by cawilliamson** [oracle-terraform-modules/terraform-oci-oke#19]
It seems odd to me (and certainly not in keeping with other cloud providers) that SSH keys would need to be provided in the form of static files to spin up a k8s cluster.

If the keys cannot be generated in the cloud itself then it would make sense (in my opinion) to generate them using the `tls_private_key` terraform resource so they can be stored along with everything else in the TF statefile (and Consul if required.)

**Comment by hyder** [comment]
The ssh keys are needed for the bastion and worker nodes. Even for the worker nodes, it's optional. See here: https://www.terraform.io/docs/providers/oci/r/containerengine_node_pool.html

However, currently in the nodepool code, we have not yet made it optional.

**Comment by cawilliamson** [comment]
Is this something you plan on addressing?

I'd strongly prefer to not have to provide ssh credentials during spinning up an OKE cluster if they can be instead generated at the OCI end.

**Comment by hyder** [comment]
OCI does not generate SSH keys currently. They need to be created using either openssh or you can also use Terraform's TLS provider to generate one for you.

**Comment by hyder** [comment]
The reason we don't generate the ssh keys in oci itself is so that we never see users' private keys. As users are expected to generate them locally, the keys don't need to travel over the network. This is more secure.

As I mentioned previously, the key pairs can be generated locally using Terraform's TLS provider or they can be generated manually using openssh.
