### ISSUE TITLE
v2.3.2 no longer deploys node_pool's

### ISSUE THREAD

**Issue by bieksaz** [oracle-terraform-modules/terraform-oci-oke#207]
### Terraform Version and Provider Version

$ terraform version
Terraform v0.12.29

### Affected Resource(s)

module.oke.oci_containerengine_node_pool.nodepools

## plan debug output
https://gist.github.com/bieksaz/de9ca6ca6b2d19425ac5a8368eb0dd11#file-qh-plan-log

## apply output
https://gist.github.com/bieksaz/e9d1937d164b223f0524a35a1f5af432#file-qh-apply-log

### Expected Behavior

nodepools["np1"] should have created nodes as per configuration:

  node_pools                           = {
    np1 = ["VM.Standard.E2.1", 1]
  }

### Actual Behavior

after 10 minutes (defined on provider with parameter retry_duration_seconds = 600 ) it timedout and apply failed. Without this parameter same happens in 2 minutes.

### Steps to Reproduce

run apply script

### Important Factoids

This issue does not happen on earlier version of terraform-oci-oke (v2.2.2), but now on latest version v.2.3.2 it fails. The reason to move to 2.3.2 is because of no longer working kubectl on v2.2.2

**Comment by hyder** [comment]
Hi, 

Please make sure you set an exact value for the kubernetes_version parameter. The previous default value of 'LATEST' will not work anymore due to the need to support upgrades.

Also, please note there was a slight typo in the 2.3.2 terraform.tfvars.example file. See #200. It's now fixed and merged in master: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/terraform.tfvars.example#L133

Let us know if that fixes the problem.

**Comment by hyder** [comment]
node_pool_image_id should be "none". In previous versions, this was in upper case. We'll add this to the changelog

**Comment by hyder** [comment]
fixed in #208
