### ISSUE TITLE
local-exec and bash misusage and against Terraform idea

### ISSUE THREAD

**Issue by daroga0002** [oracle-terraform-modules/terraform-oci-oke#238]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

it is not related to any particular version of terraform

### Affected Resource(s)

this is design issue

### Terraform Configuration Files

module code

### Debug Output

n/a

### Panic Output
n/a

### Expected Behavior

everything should fallow declarative IaaC pattern

### Actual Behavior

I want to discuss overall pattern related to `oracle-terraform-modules` and this repository. In general there is a lot of wrong patterns related to usage a local-exec and remote-exec provisioners which are not following overall declarative IaaC approach. A lot of things is done using some scripts and mentioned provisioner which in general against Terraform idea and causing that code hosted here is imperative (instead declarative). Terraform docs state:

```
Note: Provisioners should only be used as a last resort. For most common situations there are better alternatives. For more information, see the main Provisioners page.
```
I want open discussion about it so any feedback is welcome

### References

https://www.terraform.io/docs/provisioners/local-exec.html

**Comment by hyder** [comment]
Hi,

Thanks for initiating this discussion. In general, we have tried to keep the use of scripts to a minimum unless not possible to achieve using Terraform or the provider at this point. 

That being said, I would like to hear your suggestions on how we can reduce the use of bash scripts and improve the module.

**Comment by hyder** [comment]
@daroga0002 We are still waiting for your suggestions

**Comment by daroga0002** [comment]
Sorry I was quite busy because Black week challenges.

So from my side I imagine this that:
- all optional things like helm, calico, metrics-servers etc. as moved to other sub-module (for example oke-bootstrap or etc.). Explanation behind this is that not all customers want to use this, I know we can optionally disable/enable this but for clearance I would just push this to submodule.
- mentioned above submodule will be maintained via terraform providers: 
  - https://registry.terraform.io/providers/hashicorp/helm 
  - https://registry.terraform.io/providers/hashicorp/kubernetes
- goal is to remove any local-exec or remote-exec providers
- drain scripts or any maintenance things will be moved to separate repo as tools (in general replacement of nodes in real environment will be always two step action: add new node pool > migrate workload > remove node pool)

**Comment by hyder** [comment]
Thanks for your feedback. Very much appreciated.

Firstly, our goal is not just to provision the Kubernetes cluster but also simplify where possible the life of the K8s admin, hence the installation of tools such as helm, calico etc.

Now, for helm, we only install the client on the operator host and that's because the operator is already maintained in an independent sub module (see https://github.com/oracle-terraform-modules/terraform-oci-operator). The helm/kubernetes providers are not used.

Others are features requested by other customers e.g. metrics-server is needed for HPA, calico for network security policy. The addition of these features to the cluster using Terraform's declarative model only is currently not possible.

Similarly, the drain scripts were requested by another user (see https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/178).

If you would like these to be handled using Terraform only, can I suggest you raise these features as enhancement requests on the OCI provider repo? We'll add them as soon as they are available in the provider.

**Comment by daroga0002** [comment]
I understand your position here to make it easy for DEV, from second side I am more from OPS. All local-exec, remote-exec and scripted things are causing that `production` deployment will be not working for me (for example terraform cloud either OCI resource manager). 


I think I will just need to write my own module to handle that case

**Comment by hyder** [comment]
You can fork and comment those that you don't need?

**Comment by daroga0002** [comment]
👍

**Comment by hyder** [comment]
Also, we don't make this easier just for dev. We also want to make it easier for ops. 

That being said, there are things that some of our users request that are not achievable by the provider or need to be completed in a specific order.  In this case, we need to look at the pragmatic approach that is mentioned in the link above and use scripts. Most of those are remote-exec, only 1 is local-exec (I think). 

As I mentioned above, if the scripts don't meet your operational criteria and you want to run a completely immutable approach, feel free to comment those that you don't need.
