### ISSUE TITLE
attaching custom new security list to existing subnet with terraform

### ISSUE THREAD

**Issue by bieksaz** [oracle-terraform-modules/terraform-oci-oke#242]
Hi, I have a question to which I cant find any terraform resources or cases in google:
I create a new security list using terraform-oci-tdf-network-security module, which I want to attach to a workers subnet  autocreated with terraform-oci-oke module.  As per terraform-oci-oke module configuration, I cant find a way to configure security lists, seems this option does not exist there, only default lists with default rules are created for each subnet it creates.  On the other hand, terraform-oci-tdf-network-security module can also only create security lists, but not attach it to an existing subnet.  
Do you know how can one attach an existing security list to an existing subnet?  I cant also find any default terraform resources for this..  It seems to me like a feature unimplemented.. ?

**Comment by hyder** [comment]
Hi. 

Security list has always been independent of subnets i.e. you can always create them on their own. However, security lists were required for subnets. They are now optional.

Adding an existing security list to a subnet can be done by modifying the security_list_ids parameter which takes an array: see here: https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_subnet. It's part of the core subnet resource itself.

This is exactly what we are doing: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/modules/okenetwork/subnets.tf#L11 , https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/modules/okenetwork/subnets.tf#L22 and https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/modules/okenetwork/subnets.tf#L35. 

The security lists we are creating are those that are required by OKE docs.

Please elaborate on your use case and what you think we have missed. We'll definitely consider it.

**Comment by bieksaz** [comment]
So I understand that currently the only way to add security list to subnet is via subnets creation resource  oci_core_subnet. But thats not good enough, as theoretically (as you mentioned, security lists are separate from subnets) - they cant be created standalone, so there must also be an option to assign a security list to an existing subnet (subnets can have more than just one single security list assigned). My use case here is that once I create my workers and other subnets cia your oci-oke  modules, I get default subnets provided by this module with their default security lists. Yes, that works as a default, but now that I need some new functionality (in my case I need some special access from operator to worker subnet on specific ports which dont go by default), I can do that manually via GUI by creating new security list with new rules and assigning it to an existing subnet,   BUT, the very same thing I cannot do via terraform, because there is a resource to create security list with its rules, but there is no resource to assign this new security list to any possible subnet.  This is my issue

**Comment by hyder** [comment]
The security_list_ids parameter takes a list. In the repo, we are passing a list of 1 sec list. 

You can create other sec lists and include their ids in the aray. 

How you create the sec lists is up to you. Since you mentioned you want some ports opened, you can check how we adding optional ssh access from bastion to the worker nodes i.e. include the ports in the existing sec lists. Another option would be to create your sec list alongside the defauly worker sec lists in the okenetwork module. 

Since you also mentioned using the tdf seclist module, you can use this too. You'll need to either create it as a subrepo in your git ok or use it as a remote module. You'll also need to output the seclist ids it created and pass them as a parameters to the okenetwork module and add them to the security_list_ids parameter.

Hope that hells.

**Comment by hyder** [comment]
@bieksaz have we answered your question?

**Comment by hyder** [comment]
Hi,

I'm closing this issue. If this is still a problem, please reopen.

**Comment by lodotek** [comment]
@bieksaz how did you work around this?

**Comment by harlanbarnes** [comment]
I think the challenge the OP was trying to accomplish is something I just realized I have to deal with.

Example, you might have two stacks ...

1. VCN, subnets, routing tables, security lists, etc.
2. A stack for something else that creates a new security list that needs to be "attached" to the subnet.

The only solution is to follow a process of:

1. Apply the VCN stack with subnets, etc.
2. Apply the something-else-stack with the new security list.
3. Go BACK to the VCN stack and modify whatever variable has the security lists to attach to the subnet.

In other providers is the concept of individual sub-resources ... in this case, something like a `oci_subnet_security_list_attachment` that would accept a `subnet_id` and a `security_list_id`. (I presume we don't have that because the OCI API doesn't support it, I'm just saying.) If that attachment resource existed, we could pass in the subnet id (or find the convention or however you like) into the something-else-stack and then just attach the new security list to it.

And while I'm getting cooked up over this (my original reason for dealing with this), the OCI Redis Cluster will automatically create a security list and attach it to the subnet you provide and allow ALL the CIDR space in the VCN to connect to the Redis cluster just created.

So now you create a VCN stack, go and create your redis cluster, and your VCN stack is immediately drifted from your defined stack. You have to go find the secret security list (because it is not an attribute of the cluster) and go back to your VCN stack to add it to a variable just so your drift detection isn't sending alarms.

**Comment by aleksandr-seleznyov** [comment]
This issue should be reopened.

I have the same issues as the previous commenter. 
I have two stacks: company-sourced and my internal addition to the open one. I need to create an additional security list and attach it to the subnets.

Meanwhile any ideas on how to work this around?
