### ISSUE TITLE
[Feature] Allow KMS integration for non-admin users with existing dynamic groups

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-oke#325]
A user that will apply this module must be an admin of a tenancy to make OKE to OCI Vault integration possible.

There are few things that stopping the regular users from using full OCI Vault integration and one of those are three Dynamic Groups that this module attempts to provision:
```terraform
locals {

  dynamic_group_rule_all_clusters = (var.oke_kms.use_encryption == true) ? "ALL {resource.type = 'cluster', resource.compartment.id = '${var.compartment_id}'}" : null

  dynamic_group_rule_this_cluster = (var.oke_kms.use_encryption == true) ? "ALL {resource.type = 'cluster', resource.id = '${var.cluster_id}'}" : null

  policy_statement = (var.oke_kms.use_encryption == true) ? "Allow dynamic-group ${oci_identity_dynamic_group.oke-kms-cluster[0].name} to use keys in compartment id ${var.compartment_id} where target.key.id = '${var.oke_kms.key_id}'" : ""
}
```
OKE module must be flexible enough to reuse existing dynamic groups provided via their OCIDs instead of attempting to create new ones (and fail if a user is not an admin of a tenancy).

Ideally, as a user I'd like to use the existing dynamic group with a rule that looks like the following:
```shell
ALL {resource.type = 'cluster', resource.compartment.id = 'ocid1.compartment.oc1..aaaaaaaa2fk2dw6sdzg42slnaaevp6zzg3bgcmamxijppqiekpiveixsi2ja'}
```

**Comment by slmjy** [comment]
May be it makes sense to revive **create_policies** variable? We have similar problem - no rights to create or modify policies

**Comment by hyder** [comment]
Depends on #471. We'll re-evaluate once we add tagging suport

**Comment by devoncrouse** [comment]
Inputs added to 5.x should help:
- [create_iam_resources](https://oracle-terraform-modules.github.io/terraform-oci-oke/inputs_root.html#input_create_iam_resources) - all resources, or individually:
- [create_iam_autoscaler_policy](https://oracle-terraform-modules.github.io/terraform-oci-oke/inputs_root.html#input_create_iam_autoscaler_policy)
- [create_iam_operator_policy](https://oracle-terraform-modules.github.io/terraform-oci-oke/inputs_root.html#input_create_iam_operator_policy)
- [create_iam_kms_policy](https://oracle-terraform-modules.github.io/terraform-oci-oke/inputs_root.html#input_create_iam_kms_policy)
- [create_iam_worker_policy](https://oracle-terraform-modules.github.io/terraform-oci-oke/inputs_root.html#input_create_iam_worker_policy)
- [create_iam_defined_tags](https://oracle-terraform-modules.github.io/terraform-oci-oke/inputs_root.html#input_create_iam_defined_tags)
- [create_iam_tag_namespace](https://oracle-terraform-modules.github.io/terraform-oci-oke/inputs_root.html#input_create_iam_tag_namespace)

These should only be enabled as needed based on other configuration by default, i.e. you may not need to explicitly disable.

[Using Tags to Manage Access](https://docs.oracle.com/en-us/iaas/Content/Tagging/Tasks/managingaccesswithtags.htm) with [defined tags](https://oracle-terraform-modules.github.io/terraform-oci-oke/guide/identity_tags.html) optionally applied to created resources may also provide a solution, e.g. with a Security-approved dynamic group and access granted to USE tags for inclusion rather than write new policies/groups.

We _could_ accept existing dynamic groups as input, however you'd likely be unable to create the policies that reference them either.

Please let us know if you still run into permission issues not address by the above flags.
