### ISSUE TITLE
Best practice to deal with network

### ISSUE THREAD

**Issue by icy** [oracle-terraform-modules/terraform-oci-oke#462]
Hi,

I'd like to ask what the best way to deal with network configuration is. Looked like the new cluster really ties with a new network configuration (vcn, subnet, and so on.) What happens if I want to create two more clusters on the same network? What if we want to add more subnets so that other team can use them quickly? What if I want to destroy the very first cluster (which also provisioned the VCN for the rest)?

To be specific, what is the design decision that almost enforces (by default) users to create new network resources (https://github.com/oracle-terraform-modules/terraform-oci-oke/tree/main/modules) while what they really mean is to create new k8s cluster?

Please fix me if I've missed something.

Thanks a lot.

**Comment by icy** [comment]
This is the default one: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/docs/topology.adoc#default-deployment 

but I don't think that's suitable for most production setup. In a production setup, we really want to separate Network code with K8s code, and so on. We also want to have multiple k8s clusters on the same subnets.

**Comment by hyder** [comment]
Hi,

First of all, sorry for the delay in replying to you. 

This module is designed as a self-contained module with sensible defaults. So, it will create the required network infrastructure based on your [preferred topology ](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/docs/topology.adoc).

We do recognize however that 1 size does not fit all and that users may have different requirements. We had an attempt in the past of trying to enable the reuse of an existing VCN. However, the effort was too big then - perhaps because Terraform itself was at that time. 

We've recently had a few requests about re-using VCN and subnets. We'll look into this in the near future. Unfortunately, I cannot promise a date. Your ideas and suggestions are most welcome though. 

1 customer I worked with took the approach of splitting the entire module into individual ones. It gives them maximum flexibility, particularly with regards to reuse. However, they now have the responsibility to manually track changes in this module and apply them. The customer has the technical skills and time to do this in order to meet non-functional objectives. In this case, they were ok with the trade-off. 

Please evaluate carefully before going down this path.

hth.

**Comment by icy** [comment]
Hi @hyder,

Thanks for your feedback. 

I hope to see the new feature soon. And we don't think that we have enough resources to maintain our in-house terraform code as the customer you mentioned. Thanks for your suggestion though.

**Comment by hyder** [comment]
You're welcome

**Comment by JanisOrlovs** [comment]
Hello,

Currently, this OKE Terraform module is far from usable is real life. Okay, you have got all in one, where you can't turn off not needed components. OCI is an enterprise-focused cloud, most cases networking is split from other teams and in different blast radiuses.  If we look on your competitors, like AWS and/or GCP, then their Kubernetes modules contain only deployment for GKE or EKS, not whole other things. If you need it, then include as examples. 

Another approach would be to update the submodule for OKE, to make it compliant for Terraform registry. To be recognized as standalone submodule (to be valid)

I know there is quick start modules, that solve network problems, but there are very basic in other terms.
