### ISSUE TITLE
Permissioned Denied - Terraform OKE (dev operator)

### ISSUE THREAD

**Issue by btcdevops-apps** [oracle-terraform-modules/terraform-oci-oke#492]
Hello,
I am trying out terraform 1st time on OCI.
I've followed the quick start guide to setup the OKE cluster however I am unable to ssh into the dev operator instance.
I can however connect to the bastion instance.

`ssh -i /path/on/disk/instance_key_220308 -J opc@123.41.251.111 opc@xx.x.x.xx
opc@123.41.251.111: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
kex_exchange_identification: Connection closed by remote host`

Kindy assist

**Comment by hyder** [comment]
Hi, by default, ssh searches for `id_rsa` or `id_dsa` in $HOME/.ssh/. If your key is either somewhere else or does not use the default name, you need to let it know which keys are available for authentication purposes. To do that, you can use ssh-agent:

`
eval "$(ssh-agent -s)" 
ssh-add /path/on/disk/instance_key_220308
`

Then you should be able to ssh. It works for bastion because of the -i flag which it's using to authenticate to the bastion but the  -i flag does not extend to hosts you are jumping to.

**Comment by btcdevops-apps** [comment]
Thanks @hyder; your solution works as recommended
