### ISSUE TITLE
How **not** to customize cloud-init.sh

### ISSUE THREAD

**Issue by mailbox171** [oracle-terraform-modules/terraform-oci-oke#501]
Hello,
about the new cloud-init feature, I would like to ask

1) There is a way not to use it, so to keep the default OKE cloud-init.sh file?

2) Dowloading from OCI console after provisioning, I see some mime-handling stuff.. is that normal?

Thanks.

```

---------------------------------------------------------------------------
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Disposition: attachment; filename="worker.sh"
Content-Transfer-Encoding: 7bit
Content-Type: text/x-shellscript
Mime-Version: 1.0

#!/bin/bash

# DO NOT MODIFY
curl --fail -H "Authorization: Bearer Oracle" -L0 http://169.254.169.254/opc/v2/instance/metadata/oke_init_script | base64 --decode >/var/run/oke-init.sh

## run oke provisioning script
bash -x /var/run/oke-init.sh

### adjust block volume size
/usr/libexec/oci-growfs -y

timedatectl set-timezone Etc/UTC

touch /var/log/oke.done
--MIMEBOUNDARY--
```

**Comment by hyder** [comment]
We added only the last 3 commands:

- growfs was requested by users when they specify boot volume size greater than the default

- timezone we added because it helps troubleshooting in the users' timezone without having to constantly do a mental maths of adding/substracting to/from UTC

- the last command was for us to know that oke provisioning has completed.

Other than the above, if you don't change anything, it will be as if you have installed with default settings.
