### ISSUE TITLE
Upgrade from v3.x to v4.x

### ISSUE THREAD

**Issue by icy** [oracle-terraform-modules/terraform-oci-oke#519]
Hi,

We are using v3.3.0, and we think it's some problems. The new version v4.x seems to have some breaking changes

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/CHANGELOG.adoc#400

May I ask if there is some guides/docs for the things and/or how to process a smooth upgrade (if possible)?

Thanks

**Comment by hyder** [comment]
Hi,

Unfortunately, no it is not possible. From 4.0.0 onwards, we stopped using the base module. Instead, we use the vcn  bastion and operator modules directly. 

There is also a substantial refactoring of the submodules such as network, oke and extensions and how the dependencies and ordering between them are handled.

Also, from 4.x onwards, there are minimum versions of Terraform and OCI provider we are setting.

Hope that helps.

**Comment by icy** [comment]
@hyder Thanks for your answer. That's a great feedback, and I expected it's mentioned in our ChangeLog or documentation. We had the hard time to figure them out before asking.

I guess our next plan is to refactor our infra-code with new module version, and import any existing resources? Do you think that's possible? Maybe we launch new cluster with existing network, but then come the question how we can configure all existing network security rules/subnets and/or how new modules work with them without intervening our work.

Any guide would be highly appreciated.

Thanks a lot.

**Comment by hyder** [comment]
Hi @icy,

Thanks for the feedback. 

We had put the note about breaking changes in the CHANGELOG. We also created a discussion topic for feedback from the community (see here: https://github.com/oracle-terraform-modules/terraform-oci-oke/discussions/322). I apologise if this was not clear enough. We are thinking of moving the documentation to GitHub pages. We'll try to do a better job. Please help us improve the docs.

Re: next plan, I strongly suggest you start with a clean infra based on 4.x and then add any extension you may have created. The reason is that a key part of the 4.0 release included a switch from security lists to NSGs. Another one is the use of conditionals on module and this simplified the code a lot. We also moved the extensions e.g. calico, metrics server etc to a new submodule. This allows us to keep the OKE module focused on the cluster itself. OKE recently released a number of enhancements e.g cloud-init, tagging of resources created by OKE and we wanted to be able to support these. Others included removing Terraform code/modules that were deprecated with Terraform 1.0 release e.g. the template module.

Hope that helps.

**Comment by 12345ieee** [comment]
I've had to do this recently as well, and our experience has been equally rough, this is what we've done:
* upgrade module, fix/replace arguments that changed names
* run `terraform state mv module.oke.module.base module.oke`, VERY IMPORTANT, this takes care of fixing all the state save for the bastion, which will be rebuilt anyway
* watch as terraform tries to create 50 or so resources due to the NSG move
* fix any remaining seclist/NSG snag remaining, I think we had to fix a couple manually to get it to go through

We were able to do this without downing the node pools, but let me tell you, it wasn't enjoyable.
There are still some plan residuals we plan to tackle once we have more time, like the bastion liking to rebuild itself, but we need to analyze that better.

**Comment by icy** [comment]
@hyder @12345ieee Thank you for your feedback. It's much appreciated.
