### ISSUE TITLE
Add option to ignore changes to node pool size

### ISSUE THREAD

**Issue by scott4589** [oracle-terraform-modules/terraform-oci-oke#763]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The oci_containerengine_node_pool resource currently has the ignore_changes lifecycle rule applied on [various attributes](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/c3d5a1aa46795ab50b7e27566d90b5984c9e3b93/modules/oke/nodepools.tf#L136) but this does not include node_config_details.size. 

This presents an issue when using the cluster autoscaler because it results in Terraform trying to revert the node count in the pool to the value specified by this variable. This behaviour may not be desired if the autoscaler has scaled up/down since the last Terraform apply operation and you want the nodes currently in place to remain unaffected following future apply operations.

The [documentation](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler.htm#:~:text=If%20you%20are%20using%20both%20Terraform%20and%20the%20Kubernetes%20Cluster%20Autoscaler%20to%20manage%20node%20pools) suggests adding the ignore_changes lifecycle rule for the node_config_details.size field, so it would be very useful to have this provided as an option here.

### New or Affected Resource(s)
oci_containerengine_node_pool

**Comment by devoncrouse** [comment]
Hi @scott4589, this is currently intentional, though I agree with the problem generally - it relates to https://github.com/hashicorp/terraform/issues/24188 for ignoring fields dynamically. Without this, the size can never be changed through the module which can be a severe limitation the other way, when the autoscaler may not even be in use.

**Comment by shb-mll** [comment]
@devoncrouse What is the proposed solution in this case - where I have k8s cluster autoscaler enabled and I want to avoid changing the node pool size with subsequent terraform apply?

**Comment by 12345ieee** [comment]
I have the opposite usecase to you that @devoncrouse mentions.

In version 5.x, which has support for the autoscale at the nodepool definition level, this module could create a different nodepool object for autoscaler=true/false with two different ignore lists.

Clearly what we all need is a dynamic terraform lifecycle I hope https://github.com/hashicorp/terraform/issues/24188 gets done soon.

**Comment by galovics** [comment]
I'm running into this right now. @devoncrouse wouldn't it be possible to just add an extra variable for the nodepool configuration that'll be used in the ignore_changes section so that we - module users - can pass extra fields to ignore if needed? 

Or even a hardcoded variable on the size parameter could be useful but at its current place, the module just makes it super inconvenient to use the cluster autoscaler.

**Comment by devoncrouse** [comment]
@galovics this is what's being requested in the TF issue referenced above, and unfortunately not yet possible afaik - `ignore_changes` can't be dynamic.

The one possible workaround I'm aware of would be to duplicate the entire node/instance pool resource definition in the project - one with and one without the lifecycle ignore - and toggle between them with an input. We'd need to ensure they were otherwise kept in sync. @hyder

**Comment by galovics** [comment]
@devoncrouse thanks for the explanation, tbf I haven't checked the referenced issue.

Question though: wouldn't it make sense to simply hardcode the node pool's size as an ignore? I know for a fact that the AWS EKS team has implemented it this way in their module because the mindset is "if you're on cloud, you should use cluster-autoscaler to manage your nodes".

I think it would make sense here as well to live with this limitation until the referenced terraform issue is fixed. In addition to the possibility to properly utilize cluster autoscaling, having a consistent experience between cloud providers (AWS & OCI) is preferred for sure.

Here's their FAQ: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-are-there-no-changes-when-a-node-groups-desired_size-is-modified
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1879

Thoughts?

**Comment by hyder** [comment]
I prefer we duplicate the worker pools definition mainly because we still have users who are managing worker pools size through Terraform and this can have serious cost implications for them.

I'm thinking we introduce a new variable, probably at a global level, similar to the https://github.com/devoncrouse/terraform-oci-oke/blob/fix-ignore-size/variables-workers.tf#L36

This way, a user can explicitly state the way they prefer worker pools are managed: terraform, autoscale, manual. The manual option would then represent oci console, sdk, cli and behave the same way like autoscale i.e. even if you run terraform again, it won't affect the size.

If the user selects "terraform" as the way they want to manage the size of their pools, resource

```
"oci_core_instance_pool" "terraformed_workers"
```

is created. Else, resource

```
resource "oci_core_instance_pool" "autoscaled_workers" 
```

is created. This also gives us the opportunity to move the resources for those existing users.

**Comment by hyder** [comment]
@galovics @12345ieee We have a new PR for this issue #936

Would it be possible for you both to try this in your environment and let us know your feedback?

**Comment by galovics** [comment]
@hyder sure, will give it a try next week. Thanks.

**Comment by 12345ieee** [comment]
Terrible timing, I'm on holiday for the month :D .

Might take a look when I get back to work if you still need.

**Comment by hyder** [comment]
@galovics good to hear that. credit to @robo-cap. 

I've a cut a new release (v5.1.8) in case you or others need this in remote modules.

**Comment by galovics** [comment]
@hyder thank you.
