### ISSUE TITLE
Cannot configure node pool when creating a oke cluster using terraform

### ISSUE THREAD

**Issue by SuperAayush** [oracle-terraform-modules/terraform-oci-oke#790]
Hey, I have been trying to provision an OKE cluster using Terraform and keep on getting this error when I hit Terraform apply:
<img width="1370" alt="error" src="https://github.com/oracle-terraform-modules/terraform-oci-oke/assets/78820926/599c4b8e-f2bf-44f4-a37e-5fdd0fd3c0c7">

Node Pool terraform file contains:

```
resource "oci_containerengine_node_pool" "oke-node-pool" {
    cluster_id = oci_containerengine_cluster.oke-cluster.id
    compartment_id = oci_identity_compartment.tf-compartment.id
    kubernetes_version = "v1.26.2"
    name = "pool1"
    node_config_details{
        placement_configs{
            availability_domain = data.oci_identity_availability_domains.ads.availability_domains[0].name
            subnet_id = oci_core_subnet.vcn-private-subnet.id
        } 
        size = 1
    }
    node_shape = "VM.Standard.E3.Flex"

    node_source_details {
         image_id = var.image_id
         source_type = "image"
    }

    initial_node_labels {
        key = "name"
        value = "oke_working_check"
    }    
}
```

Image id I am using: ocid1.image.oc1.ap-mumbai-1.aaaaaaaaikzx23h66szvs3ixo24h5dnr7b76cthpdju4l6zj3jmbt3euqfjq

**Comment by devoncrouse** [comment]
Hi @SuperAayush - looks like this is an OL9 image and not yet supported. Can you give this a try with [ocid1.image.oc1.ap-mumbai-1.aaaaaaaaepb5tnr4b2ilnbvoigmkfckn7fbkhm5leiatdqu34tqq2fdkckza](https://docs.oracle.com/en-us/iaas/images/image/48e6f7f3-0f88-4bc0-848f-ec743b180960/)?

**Comment by devoncrouse** [comment]
You can also look at [node-pool-options](https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.30.1/oci_cli_docs/cmdref/ce/node-pool-options/get.html) to enumerate available images, e.g.:

```shell
oci ce node-pool-options get --node-pool-option-id all | jq '.data.sources'
```

**Comment by SuperAayush** [comment]
Hey @devoncrouse, even after using this image I get the same error 

> Hi @SuperAayush - looks like this is an OL9 image and not yet supported. Can you give this a try with [ocid1.image.oc1.ap-mumbai-1.aaaaaaaaepb5tnr4b2ilnbvoigmkfckn7fbkhm5leiatdqu34tqq2fdkckza](https://docs.oracle.com/en-us/iaas/images/image/48e6f7f3-0f88-4bc0-848f-ec743b180960/)?

**Comment by SuperAayush** [comment]
> Hey @devoncrouse, even after using this image I get the error:
> 
> <img alt="er1" width="1183" src="https://user-images.githubusercontent.com/78820926/258367373-92fd2a9a-7504-4e32-a9c4-b4cfb35f7a59.png">
> Any advice on which k8s version should be used with the given image, I have mentioned `v1.26.2` in terraform file but still I get `v1.24.1` when my cluster is created and it suggests me to migrate to new version manually.
> 
> ![er2](https://user-images.githubusercontent.com/78820926/258367934-a86bfd54-0a23-432d-9076-91b3261e5997.png)
> 
> > Hi @SuperAayush - looks like this is an OL9 image and not yet supported. Can you give this a try with [ocid1.image.oc1.ap-mumbai-1.aaaaaaaaepb5tnr4b2ilnbvoigmkfckn7fbkhm5leiatdqu34tqq2fdkckza](https://docs.oracle.com/en-us/iaas/images/image/48e6f7f3-0f88-4bc0-848f-ec743b180960/)?

Hey @devoncrouse, any views on this?

**Comment by devoncrouse** [comment]
@SuperAayush Your example is using the upstream [OCI provider](https://registry.terraform.io/providers/oracle/oci/latest/docs) rather than this module, which provides a reference implementation of it with additional convenience features.

Please review the documentation for [containerengine_cluster](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster) and [containerengine_node_pool](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_node_pool) to further inform usage of the provider directly, and refer to the [terraform-provider-oci](https://github.com/oracle/terraform-provider-oci) project for any issues.

The created node pool should typically be configured to match the `kubernetes_version` of the targeted cluster - you've only shared the cluster configuration here, so confirm that the appropriate value is specified for the [cluster resource](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster#kubernetes_version) also.

Please try the [node-pool-options](https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.30.1/oci_cli_docs/cmdref/ce/node-pool-options/get.html) command above with your cluster specified to list available images for it, and/or compare with presented image options for in the console:

```shell
oci ce node-pool-options get --node-pool-option-id <cluster id> --compartment-id <compartment id>
```

**Comment by SuperAayush** [comment]
Hey @devoncrouse!!

It's my request if you could find some time to jump on a call and see what mistake I have made in my terraform code.
Will it be possible?
