### ISSUE TITLE
5.x: added autoscaler=true, allow_autoscaler=true to TF, but existing nodes do not have

### ISSUE THREAD

**Issue by rodrigc** [oracle-terraform-modules/terraform-oci-oke#794]
Using `5.0.0-beta-3` version of the module.
I deployed a node pool originally where the terraform was:

```
node_pools = {
  blue = {
    shape            = "VM.Standard.E4.Flex",
    ocpus            = 4,
    memory           = 32,
    size             = 6,
    boot_volume_size = 150,
    maxSize          = 9,
    node_labels = {
      "node/type" = "blue"
    }
  }
  ```
  
I then modified the terraform to this and did a `terraform apply`:
  
```
node_pools = {
  blue = {
    shape            = "VM.Standard.E4.Flex",
    ocpus            = 4,
    memory           = 32,
    size             = 6,
    boot_volume_size = 150,
    allow_autoscaler = true,
    autoscaler       = true,
    maxSize          = 9,
    node_labels = {
      "node/type" = "blue"
    }
  }
}
```

If I add `allow_autoscaler` and `autoscaler` to each node section in the terraform, is it correct that
the Kubernetes node annotations and labels on the nodes will not be updated to allow autoscaling?

If I do:

```
kubectl get nodes -o yaml
```

Every node in my cluster has:

```
labels:
  ...
  oke.oraclecloud.com/cluster_autoscaler: disabled
```

If I look at all the pods in my system, I see:

```
│kube-system           cluster-autoscaler-oci-oke-cluster-autoscaler-78f44fdb4b-k6nss  ●  0/0          0 Pending              0     0 
```

```
kubectl -n kube-system describe pod cluster-autoscaler-oci-oke-cluster-autoscaler-78f44fdb4b-k6nss 
```

```
kubectl -n kube-system describe pod 

...
QoS Class:                   BestEffort                                                                
Node-Selectors:              oke.oraclecloud.com/cluster_autoscaler=allowed                
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s                          node.kubernetes.io/unreachable:NoExecute op=Exists for 300s                                              
Events:                                                                                                                               
  Type     Reason            Age                   From               Message                                                         
  ----     ------            ----                  ----               -------                                                         
  Warning  FailedScheduling  24m (x935 over 3d6h)  default-scheduler  0/19 nodes are available: 19 node(s) didn't match Pod's node affinity/selector. preemption: 0/19 nodes are available: 19 Preemption is not helpful for scheduling.     
```

A few questions:

1.  Will the autoscaler labels be applied to newly created nodes?
2.  For existing nodes which I do not want to blue away, what are the labels/annotations that I can manually apply to the nodes to get autoscaling working?

FYI: @cwiggs @yaanakbr

**Comment by devoncrouse** [comment]
@rodrigc Labels added to a pool definition, including the `cluster_autoscaler=allowed`, will affect only newly-added nodes as with https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/770#issuecomment-1636562140.

With the dynamic group and policy created e.g. using `create_iam_autoscaler_policy = "auto"/"always"`, this label is used to enable scheduling of Cluster Autoscaler on nodes that have been granted the [necessary permissions](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler.htm#Using_the_Kubernetes_Cluster_Autoscaler) for it to manage OCI resources. The label could be added to existing nodes manually through kubectl rather than recreating them, if the permission has been granted after or with another approach. The CA deployment configuration can also be customized with [Helm input values](https://oracle-terraform-modules.github.io/terraform-oci-oke/guide/extensions_cluster_autoscaler.html#usage) e.g. to change the [nodeSelector](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/modules/extensions/autoscaler.tf#L62).

**Comment by rodrigc** [comment]
Question answered
